### ISSUE TITLE
Menu screen

### ISSUE THREAD

**Issue by Leva7** [MoarCatz/chat#2]
Create a menu screen

**Comment by alexbagirov** [comment]
Closed in https://github.com/MoarCatz/chat/commit/1d84e53b287aeb270fb9eb43cde59f53afbcb0bd.

**Comment by alexbagirov** [comment]
Reopen this as it is still in progress.

**Comment by alexbagirov** [comment]
:+1: 

![9288_0](https://cloud.githubusercontent.com/assets/6885864/18225743/cf7a274e-7213-11e6-95f2-eb2456111326.jpg)
